name: Build Container Image
on:
  push:

jobs:
  build:
    name: Build and Upload Container
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install qemu dependency
      run: |
        sudo apt-get -y update
        sudo apt-get -y install qemu-user-static

    - name: Tag :latest on main Branch
      id: tag-latest
      run: |
        if [ ${{github.ref_name}} == main ]; then
          echo '::set-output name=tags::'latest
        else
          echo '::set-output name=tags::'
        fi

    - name: Build Podman Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{github.repository}}
        tags: githash_${{github.sha}} ${{github.ref_name}} ${{steps.tag-latest.outputs.tags}}
        archs: arm64
        containerfiles: |
          ./Containerfile

    - name: Login to ghcr.io
      id: podman-login
      uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{github.token}}

    - name: Push to Registry
      id: push-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        registry: ghcr.io
        image: ${{steps.build-image.outputs.image}}
        tags: ${{steps.build-image.outputs.tags}}

    - name: Print Image URL
      run: echo "Image pushed to ${{steps.push-to-ghcr.outputs.registry-paths}}"
